STOP SLAVE;
RESET MASTER;
RESET SLAVE;
CHANGE MASTER TO MASTER_HOST='{{MASTER_HOST}}', MASTER_PORT={{MASTER_PORT}}, MASTER_USER='sync', MASTER_PASSWORD='123456', MASTER_CONNECT_RETRY=5;
START SLAVE;
FLUSH PRIVILEGES;